version: "3.2"

# networks:
#   consul-network:
#     driver: bridge

services:

  eventstore:
    container_name: eventstore-node
    ports:
      - '2113:2113'
      - '1113:1113'
    image: eventstore/eventstore:release-5.0.8
    labels:
      kompose.service.type: nodeport
      kompose.service.expose: "true"
      kompose.image-pull-policy: "Always"
  db:
    image: postgres
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
     - "27017:27017"

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
     - "6379:6379"
