version: 2.1
orbs:
  node: circleci/node@4.4.0


jobs:
  build-test-and-deploy:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.large
    steps:
      - checkout
      - node/install:
          install-npm: false
          node-version: 14.17.0
      - node/install-yarn:
          version: 1.22.4
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: yarn affected:build --base=<< pipeline.git.base_revision >> --head=HEAD
          no_output_timeout: 1h

      - run:
          command: yarn affected --target=deploy --base=<< pipeline.git.base_revision >> --head=HEAD
          no_output_timeout: 1h

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy:
          context:
            - NETLIFY