version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn affected:build --base=<< pipeline.git.base_revision >> --head=HEAD
      - run: yarn affected -- --target=deploy --base=<< pipeline.git.base_revision >> --head=HEAD

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy