version: 2.1
orbs:
  node: circleci/node@4.4.0


jobs:
  build-test-and-deploy:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/default:
          tag: '14.17.0'
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn affected:build --base=<< pipeline.git.base_revision >> --head=HEAD
      - run: yarn affected --target=deploy --base=<< pipeline.git.base_revision >> --head=HEAD

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy